---
R1:
    hostname: 192.168.30.11
    port: 22
    groups:
        - rtrs
    data:
        oob_port: 32897
        type: router
R2:
    hostname: 192.168.30.12
    groups:
        - rtrs
    data:
        oob_port: 32898
        type: router
R3:
    hostname: 192.168.30.13
    groups:
        - rtrs
    data:
        oob_port: 32899
        type: router
SW4:
    hostname: 192.168.30.14
    groups:
        - sws
    data:
        oob_port: 32900
        type: switch
SW5:
    hostname: 192.168.30.15
    groups:
        - sws
    data:
        oob_port: 32901
        type: switch
SW6:
    hostname: 192.168.30.16
    groups:
        - sws
    data:
        oob_port: 32902
        type: switch
SW7:
    hostname: 192.168.30.17
    groups:
        - sws
    data:
        oob_port: 32903
        type: switch
SW8:
    hostname: 192.168.30.18
    groups:
        - sws
    data:
        oob_port: 32904
        type: switch
SW9:
    hostname: 192.168.30.19
    groups:
        - sws
    data:
        oob_port: 32906
        type: switch
